### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by OcelotWalrus** [ZeroedInOnTech/mcpbuilds#5]
Is it possible to add .zip in release section of this github for download more faster the mcp pre-decompiled?
Because i have download the pre-decompiled but the eclipse workspace is empty...

**Comment by OcelotWalrus** [comment]
See:
https://drive.google.com/file/d/1QefucKdSGiaItPhXEaMNt_ZebRT45_75/view?usp=sharing

**Comment by luhgarlicbread** [comment]
I think you have to select the eclipse folder in the downloaded pre-decompiled ModCoderPack.

**Comment by OcelotWalrus** [comment]
It's what i have do

**Comment by OcelotWalrus** [comment]
OH I have download again and this time it's works,
THX
